version: '3.8'

services:
  # Simple local dashboard (optional)
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "${DASHBOARD_PORT:-8080}:8080"
    environment:
      - NODE_ENV=development
      - DB_PATH=/app/data/arbitrage_data.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - watcher
    restart: unless-stopped

  # Price watcher service
  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/arbitrage_data.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    env_file:
      - .env
    restart: unless-stopped

  # Optional: Simple log viewer
  logs:
    image: amir20/dozzle:latest
    container_name: arbitrage-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9999:8080"
    profiles:
      - monitoring

volumes:
  data:
    driver: local
  logs:
    driver: local

networks:
  default:
    name: arbitrage-network 