[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

# Solidity compiler settings
solc = "0.8.19"
optimizer = true
optimizer_runs = 200
via_ir = true

# Testing settings
verbosity = 2
fuzz_runs = 1000
fuzz_max_test_rejects = 65536

# Gas settings
gas_limit = 30000000
gas_price = 20000000000

# RPC settings
eth_rpc_url = "https://eth-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
arbitrum_rpc_url = "https://arb-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
avalanche_rpc_url = "https://api.avax.network/ext/bc/C/rpc"

# Testnet RPCs
sepolia_rpc_url = "https://eth-sepolia.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
arbitrum_sepolia_rpc_url = "https://arbitrum-sepolia.infura.io/v3/YOUR_INFURA_KEY"
avalanche_fuji_rpc_url = "https://api.avax-test.network/ext/bc/C/rpc"

# Etherscan settings
etherscan_api_key = "YOUR_ETHERSCAN_API_KEY"
arbiscan_api_key = "YOUR_ARBISCAN_API_KEY"
snowtrace_api_key = "YOUR_SNOWTRACE_API_KEY"

# Verification settings
verify = true
etherscan_base_url = "https://api.etherscan.io/api"

[profile.ci]
fuzz_runs = 10000

[profile.lite]
optimizer = false
optimizer_runs = 200

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[doc]
out = "docs"
title = "Cross-Domain Arbitrage Bot"
book = "book.toml"
homepage = "https://github.com/your-org/chainlink-arbitrage-bot"

[dependencies]
"@openzeppelin/contracts" = "5.0.0"
"@chainlink/contracts" = "0.8.0"
"solmate" = { git = "https://github.com/transmissions11/solmate.git", tag = "v6" }

# Network configurations
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"
arbitrum_sepolia = "https://arbitrum-sepolia.infura.io/v3/YOUR_INFURA_KEY"
avalanche = "https://api.avax.network/ext/bc/C/rpc"
avalanche_fuji = "https://api.avax-test.network/ext/bc/C/rpc" 